server:
  port: 8082

spring:
  application:
    name: product
  datasource:
    username: 'root'
    password: ''
    url: jdbc:mysql://localhost:3306/products
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html