server:
  port: 8082

spring:
  application:
    name: fraud
  datasource:
    username: 'root'
    password: ''
    url: jdbc:mysql://localhost:3306/frauds
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true