server:
  port: 8083

spring:
  application:
    name: reviews
  datasource:
    username: 'root'
    password: ''
    url: jdbc:mysql://localhost:3306/reviews
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true